const posts = [
  {
    _id: '1',
    title: 'Web development',
    description: 'I will build website for you',
    username: 'Hank',
    location: 'Winnipeg',
    createdOn: '07-31-2020',
    myTalent: 'Web Dev',
    wantedTalent: 'Leather crafting',
    numReplies: 4,
    views: 5,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '2',
    title: 'Mobile development',
    description: 'I will build website for you',
    username: 'Hank',
    location: 'Winnipeg',
    createdOn: '07-31-2020',
    myTalent: 'Web Dev',
    wantedTalent: 'Leather crafting',
    numReplies: 4,
    views: 5,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '3',
    title: 'Desktop development',
    description: 'I will build website for you',
    username: 'Hank',
    location: 'Winnipeg',
    createdOn: '07-31-2020',
    myTalent: 'Web Dev',
    wantedTalent: 'Leather crafting',
    numReplies: 4,
    views: 5,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '4',
    title: 'App development',
    description: 'I will build website for you',
    username: 'Hank',
    location: 'Winnipeg',
    createdOn: '07-31-2020',
    myTalent: 'Web Dev',
    wantedTalent: 'Leather crafting',
    numReplies: 4,
    views: 5,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '5',
    title: 'System development',
    description: 'I will build website for you',
    username: 'Hank',
    location: 'Winnipeg',
    createdOn: '07-31-2020',
    myTalent: 'Web Dev',
    wantedTalent: 'Leather crafting',
    numReplies: 4,
    views: 5,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    title: 'Hardware development',
    description: 'I will build website for you',
    username: 'Hank',
    location: 'Winnipeg',
    createdOn: '07-31-2020',
    myTalent: 'Web Dev',
    wantedTalent: 'Leather crafting',
    numReplies: 4,
    views: 5,
    rating: 3.5,
    numReviews: 10,
  },
];

export default posts;
